bie.evgestao/1 - UI/1.1 - MVC/bie.evgestao.ui.mvc/Controllers/CelulasController.cs

using AutoMapper;
using bie.evgestao.application.Interfaces;
using bie.evgestao.domain.Entities;
using bie.evgestao.domain.Enums;
using bie.evgestao.ui.viewmodels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace bie.evgestao.ui.mvc.Controllers
{
    [Authorize]
    public class CelulasController : BaseController
    {

        #region Constructor 
        private readonly IPessoaAppService _svcPessoa;
        private readonly ICelulaAppService _svcCelula;

        public CelulasController(IPessoaAppService Svc1, ICelulaAppService Svc2)
        {
            _svcPessoa = Svc1;
            _svcCelula = Svc2;
        }

        #endregion




        // GET: Celula
        //Retorna somente a view pois a mesma usa uma chamada ajax pra popular o grid
        [Authorize]
        public ActionResult Index()
        {
            return View();
        }


        #region Criar

        [HttpGet]
        [Authorize(Roles = "Superadmin,Administrador,Secretaria")]
        public ActionResult Criar()
        {
            #region preparação
            ViewBag.PessoasDisponiveis = Mapper.Map<IEnumerable<Pessoa>, IEnumerable<PessoaViewmodel>>(_svcPessoa.GetAll());
            #endregion

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Superadmin,Administrador,Secretaria")]
        public ActionResult Criar(CelulaViewmodel model)
        {
            try
            {
                #region preparação
                ViewBag.PessoasDisponiveis = Mapper.Map<IEnumerable<Pessoa>, IEnumerable<PessoaViewmodel>>(_svcPessoa.GetAll());
                #endregion

                //valida se não há erros no modelstate (caso o jquery validation falhe)
                if (!ModelState.IsValid) return View(model);


                //mapeia a entidade
                var objEntidade = Mapper.Map<CelulaViewmodel, Celula>(model);

                //insere a entidade
                _svcCelula.Add(objEntidade);

                //seta a mensagem de sucesso que será exibido pelo javascript
                ViewBag.Mensagem = "Item criado com sucesso";

                //retorna pra lista
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                //seta a mensagem de falha
                ViewBag.Mensagem = $"Erro ao processar o comando o erro foi: {ex.Message}";
                return View(model);
            }
        }


        #endregion


        #region Editar

        [HttpGet]
        [Authorize(Roles = "Superadmin,Administrador,Secretaria")]
        public ActionResult Editar(int id)
        {
            #region preparação
            ViewBag.PessoasDisponiveis = Mapper.Map<IEnumerable<Pessoa>, IEnumerable<PessoaViewmodel>>(_svcPessoa.GetAll());
            #endregion

            var entidade = _svcCelula.GetById(id);

            var model = Mapper.Map<Celula, CelulaViewmodel>(entidade);

            return View(model);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Superadmin,Administrador,Secretaria")]
        public ActionResult Editar(CelulaViewmodel model)
        {
            try
            {
                #region preparação
                ViewBag.PessoasDisponiveis = Mapper.Map<IEnumerable<Pessoa>, IEnumerable<PessoaViewmodel>>(_svcPessoa.GetAll());
                #endregion

                //valida se não há erros no modelstate (caso o jquery validation falhe)
                if (!ModelState.IsValid) return View(model);

                //carerga a entidade da celula no banco de dados
                var entidade = _svcCelula.GetById(model.id_celula);

                //faz um backup dos participantes pois o Automapper zera os itens filho que não encontrados
                var bkp_pessoas = entidade.Pessoas.ToList();

                //faz o mapeamento das propriedades 
                Mapper.Map<CelulaViewmodel, Celula>(model, entidade);

                //retorna alista de pessoas
                entidade.Pessoas = bkp_pessoas;

                //executa o update no banco 
                _svcCelula.Update(entidade);

                //retorna a mensagem de sucesso que será exibida pelo javascript 
                ViewBag.Mensagem = "Item modificado com sucesso";

                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                //seta mensagem de falha
                ViewBag.Mensagem = $"Erro ao processar o comando o erro foi: {ex.Message}";
                return View(model);
            }

        }

        #endregion


        #region Visualizar 

        [Authorize]
        public ActionResult Celula(int id)
        {
            //Carrega a entidade do banco de dados 
            var objEntidade = _svcCelula.GetById(id);
            if (objEntidade == null) return new HttpNotFoundResult("Celula não encontrada");
            var model = Mapper.Map<Celula, CelulaViewmodel>(objEntidade);
            return View(model);
        }


        #endregion

        #region Participantes

        [HttpGet]
        [Authorize(Roles = "Superadmin,Administrador,Secretaria")]
        public ActionResult Participantes(int id)
        {

            #region preparação
            ViewBag.PessoasDisponiveis = Mapper.Map<IEnumerable<Pessoa>, IEnumerable<PessoaViewmodel>>(_svcPessoa.GetAll());

            var Situacoes = Helpers.EnumToDropDownListExtensions.GetSelectListFromEnum(SituacaoPessoa.COMUNGANTE);
            ViewBag.Situacoes = Situacoes;

            #endregion



            //carreg aa celula 
            var model = Mapper.Map<Celula, CelulaViewmodel>(_svcCelula.GetById(id));
            if (model == null) throw new HttpException(404, "Item não encontrado");

            return View(model);


        }

        #endregion



        #region Multiplicação 

        [HttpGet]
        [Authorize(Roles = "Superadmin,Administrador,Secretaria")]
        public ActionResult Multiplicar()
        {

            #region preparacao 


            //TODO: Gustavo. Verificar pois na regra de negócio nada impede o cara de ser coordenador de mais de uma celula
            var CelulasDisponiveis = from celula in _svcCelula.GetAll()
                                     where celula.Coordenador != null
                                     select new MultiplicarCelulasDisponiveisViewmodel
                                     {
                                         NomeCoordenador = celula.Coordenador.Nome,
                                         id_celula = celula.id_celula,
                                         NomeSupervisor = celula.Supervisor != null ? celula.Supervisor.Nome : string.Empty
                                     };

            ViewBag.CelulasDisponiveis = CelulasDisponiveis.ToArray();


            //lista as pessoas disponíveis para ser coordenador ou supervisor da nova célula
            ViewBag.PessoasDisponiveis = Mapper.Map<IEnumerable<Pessoa>, IEnumerable<PessoaViewmodel>>(_svcPessoa.GetAll());

            //carrega o ultimo numero de celula disponivel             
            var ProximaCelula = _svcCelula.GetAll().Last().id_celula + 1;
            ViewBag.ProximaCelula = ProximaCelula.ToString().PadLeft(4, '0');






            #endregion


            return View();
        }

        [HttpPost]
        [Authorize(Roles = "Superadmin,Administrador,Secretaria")]
        public JsonResult Multiplicar(MultiplicarCelulaViewmodel model)
        {
            try
            {
                //carrega a celula de origem
                var entidadeCelulaOrigem = _svcCelula.GetById(model.id_origem);

                //cria a nova celula 
                Celula entidadeCelulaDestino = new Celula();



                //seta as propriedades
                entidadeCelulaDestino.Nome = entidadeCelulaOrigem.Nome + " Nova";
                entidadeCelulaDestino.id_coordenador = model.id_coordenador;
                entidadeCelulaDestino.id_supervisor = model.id_supervisor;
                entidadeCelulaDestino.DataCriacao = DateTime.Now;
                entidadeCelulaDestino.TipoCelula = entidadeCelulaOrigem.TipoCelula;
                entidadeCelulaDestino.Ativo = true;


                //cria  a nova celula 
                _svcCelula.Add(entidadeCelulaDestino);

                //Adiciona as pessoas 
                foreach (var id_pessoa in model.Membros)
                {
                    _svcCelula.InsereParticipante(entidadeCelulaDestino.id_celula, id_pessoa, SituacaoPessoa.OUTROS);
                }


                return Json(new { staus = "sucesso", entidadeCelulaDestino.id_celula });

            }
            catch (Exception ex)
            {

                throw new HttpException(500, $"Erro ao executar comando no servidor. o Erro foi: {ex.Message}");

            }



        }



        #endregion




        #region API
        /// <summary>
        /// Método genérico para retornar a lista de itens da entidade para carregar a página inicial
        /// </summary>
        /// <returns></returns>
        /// 
        public JsonResult GetJson()
        {
            //instancia as entidades já carregando do serviço 
            var entidade = _svcCelula.GetAll();
            //Mapeia para a viewmodel --> não se deve retornar o modelo direto sem uma viewmodel pois como ele tem muitos relacionamentos, pode arriscar
            //carregar todos os dados do sistema no mesmo ajax, o que travaria o navegador e o servidor 

bie.evgestao/1 - UI/1.1 - MVC/bie.evgestao.ui.mvc/Views/Celulas/Index.cshtml

@{
    ViewBag.Title = "Gerenciar Células";
    ViewBag.HeaderText = ViewBag.Title;

    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div id="page-title">
    <h2>Gerenciar Células</h2><p>
        Gestão de células e participantes
    </p>
</div>
<div class="row">

    <div class="col-md-12" style="padding-bottom:20px;">
        @Html.ActionLink("Adicionar Célula", "Criar", null, new { @Class = "btn btn-primary" }) &nbsp;
        @Html.ActionLink("Multiplicação", "Multiplicar", null, new { @Class = "btn btn-primary" })

    </div>


    <div class="col-md-12">
        <table class="table " id="tblMain">
            <thead>
                <tr>
                    <th>Célula</th>
                    <th>Tipo</th>
                    <th>Coordenador</th>
                    <th style="text-align:center" class="text-center">Situação</th>
                    <th style="text-align:center" class="text-center">Tels</th>
                    <!-- botões de ações-->
                    <th style="width:230px; text-align:center;" class="text-center"></th>
                </tr>
            </thead>
        </table>

    </div>
</div>



<!-- Modal -->
<div class="modal fade" id="mdConfirmDelete" tabindex="-1" role="dialog" aria-labelledby="mdConfirmDeleteLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="mdConfirmDeleteLabel">Confirma exclusão da célula</h4>
            </div>
            <div class="modal-body">
                Deseja mesmo excluir este item? Todos os dados serão excluídos inclusive os participantes.
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                <button type="button" class="btn btn-danger" id="btnExcluir">Excluir</button>
            </div>
        </div>
    </div>
</div>

@section precss {

}
@section header {
}
@section scripts {

    <script src="~/Content/3rdParty/Template/widgets/datatable/datatable.js"></script>
    <script src="~/Content/3rdParty/Template/widgets/datatable/datatable-bootstrap.js"></script>
    <script src="~/Content/3rdParty/Template/widgets/datatable/datatable-tabletools.js"></script>

    <script src="~/Content/3rdParty/Template/widgets/modal/modal.js"></script>
    <script type="text/javascript">


        var tabela;

        $(document).ready(function () {

            tabela = $('#tblMain').DataTable({
                responsive: true,
                language: { url: '@Url.Content("~/content/ptbr.json")' },
                ajax: '@Url.Content("~/celulas/getjson")',
                columns: [
                    {
                        data: "Nome",
                        title: "Celula"
                    },
                    {
                        data: "TipoDesc",
                        title: "Tipo"
                    },
                    {
                        data: "NomeCoordenador",
                        title: "Coordenador"
                    },
                    {
                        data: "SituacaoDesc",
                        title: "Situação"
                    },
                    {
                        data: "Tels",
                        title: "Tels"
                    },
                     {
                         data: "id_celula",
                         title: "Ações",
                         bSortable: false,
                         render: function (o, tipo, linha) {
                             var urlBase = '@Url.Content("~/celulas/editar/")';
                             var urlParticipantes = '@Url.Content("~/celulas/participantes/")';
                             var urlVisualizar = '@Url.Content("~/celulas/celula/")';



                             var ret = "<div style='width:100%;' class='text-center' id='dv-botoes'>";

                             //botão visualizar
                             ret += '<a class="btn btn-default glyph-icon icon-eye" title="Visualizar célula" href="' + urlVisualizar + o + '" role="button"><div class="ripple-wrapper"></div></a>&nbsp;';


                             //botão participantes
                             ret += '<a class="btn btn-default glyph-icon icon-child" title="Editar Participantes" href="' + urlParticipantes + o + '" role="button"><div class="ripple-wrapper"></div></a>&nbsp;';

                             //botao editar
                             ret += '<a class="btn btn-default glyph-icon icon-edit" title="Editar item" href="' + urlBase + o + '" role="button"><div class="ripple-wrapper"></div></a>&nbsp;';

                             //botao excluir
                             ret += '<button type="button" title="Remover item" class="btn btn-default btn-excluir" onclick="excluir(\'' + o + '\')" ><i class="glyph-icon icon-trash"></i><div class="ripple-wrapper"></div></button>';

                             ret += "</div>";

                             return ret;
                         }

                     }
                ],//fim columns
                order: [[1, "asc"]]


            });//fim datatables

        }); //ready




        var excluir = function (id) {
            var ml = $('#mdConfirmDelete').modal({ backdrop: 'static', keyboard: false })
                .one('click', '#btnExcluir', function (e) {

                    $.ajax({
                        url: '@Url.Content("~/celulas/deletar")',
                        dataType: "json",
                        type: "POST",
                        contentType: 'application/json; charset=utf-8',
                        data: JSON.stringify({ id: id }),
                        async: true,
                        processData: false,
                        cache: false,
                        success: function (data) {
                            $(ml).modal("hide");
                            tabela.ajax.reload();
                        },
                        error: function (xhr) {

                            var arrResp = $(xhr.responseText);

                            if (arrResp.length > 0) //A api retornou o erro, exibir o que está vindo da API
                            {
                                alert($(arrResp[1]).text());

                            } else //A api não retornou erro corretamente. Exibe mensagem genérica de erro
                            {
                                alert('Erro ao efetuar o comando no servidor');
                            }

                            $(ml).modal("hide");
                            // alert($($(xhr.responseText)[1]).text());
                        }
                    });

                });
        }//excluir







    </script>
}

bie.evgestao/1 - UI/1.1 - MVC/bie.evgestao.ui.mvc/Views/Celulas/Multiplicar.cshtml
@model bie.evgestao.ui.viewmodels.MultiplicarCelulaViewmodel
@using bie.evgestao.ui.mvc.Helpers
@using bie.evgestao.ui.viewmodels
@{
    ViewBag.Title = "Multiplicar Célula";
    ViewBag.HeaderText = ViewBag.Title;

    Layout = "~/Views/Shared/_Layout.cshtml";
}


@using (Html.BeginForm("Multiplicar", "celulas", FormMethod.Post, new { @id = "frmMain", @enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()




    <div class="col-md-12">

        <div class="panel panel-default">

            @Html.ValidationSummary(true, "", new { @class = "text-danger" })



            <div class="form-horizontal">


                <div class="form-horizontal frmlimitado" style="max-width:800px;max-height:9999px;">



                    <div class="panel-heading">
                        <h3>Celula de origem</h3>
                    </div>
                    <div class="panel-body">

                        <div class="form-group">

                            @Html.LabelFor(model => model.id_origem, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-4">
                                <div class="input-group">


                                    <select id="id_origem" name="id_origem">
                                        <option>Selecione</option>
                                        @foreach (MultiplicarCelulasDisponiveisViewmodel item in ViewBag.CelulasDisponiveis)
                                        {
                                            <option value="@item.id_celula" nomesupervisor="@item.NomeSupervisor">@item.NomeCoordenador</option>
                                        }
                                    </select>

                                    <span class="input-group-addon bg-black">
                                        <i class="glyph-icon icon-user"></i>
                                    </span>
                                    @Html.ValidationMessageFor(model => model.id_origem, "", new { @class = "text-danger" })
                                </div> <!-- input group celula de origem -->
                            </div><!-- col-md-4 da celula origem -->


                            <label for="txtnumero" class="control-label col-md-2">Número: </label>

                            <div class="col-md-4">
                                <input type="text" readonly="readonly" id="txtnumero" name="textnumero" class="form-control pequeno" />
                            </div>
                        </div><!-- from group-->

                        <div class="form-group">

                            <label for="txtsupervisor" class="control-label col-md-2">Supervisor:</label>
                            <div class="col-md-4">
                                <input type="text" readonly="readonly" id="txtsupervisor" name="txtsupervisor" class="form-control" />
                            </div>

                        </div>





                    </div><!-- Painel body -->



                    <div id="dvdestino" style="display:none">

                        <div class="panel-heading">
                            <h3>Celula de Destino</h3>
                        </div>
                        <div class="panel-body">
                            <div class="form-group">
                                @Html.LabelFor(model => model.id_coordenador, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-4">
                                    <div class="input-group">
                                        @Html.DropDownListFor(model => model.id_coordenador,
                                   new SelectList(ViewBag.PessoasDisponiveis, "id_pessoa", "Nome"), "Selecione uma pessoa", new { @class = "chosen-select form-control" })

                                        <span class="input-group-addon bg-black">
                                            <i class="glyph-icon icon-user"></i>
                                        </span>
                                        @Html.ValidationMessageFor(model => model.id_coordenador, "", new { @class = "text-danger" })
                                    </div><!-- input group-->
                                </div><!-- col-md-4-->


                                <label for="txtnumerodestino" class="col-md-2 control-label">Número:</label>

                                <div class="col-md-4">

                                    <input type="text" name="txtnumerodestino" id="txtnumerodestino" class="form-control pequeno" readonly="readonly" value="@ViewBag.ProximaCelula" />

                                </div>
                            </div>


                            <div class="form-group">
                                @Html.LabelFor(model => model.id_supervisor, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-4">
                                    <div class="input-group">
                                        @Html.DropDownListFor(model => model.id_supervisor,
                                   new SelectList(ViewBag.PessoasDisponiveis, "id_pessoa", "Nome"), "Selecione uma pessoa", new { @class = "chosen-select form-control" })

                                        <span class="input-group-addon bg-black">
                                            <i class="glyph-icon icon-user"></i>
                                        </span>
                                        @Html.ValidationMessageFor(model => model.id_supervisor, "", new { @class = "text-danger" })
                                    </div><!-- input group-->
                                </div><!-- col-md-4-->

                            </div>



                            <div class="form-group" style="padding-top:30px;">

                                <div class="col-md-5 text-center">
                                    <label for="MembrosOrigem"> Membros célula origem</label>
                                    <select multiple id="MembrosOrigem" class="form-control multi-select" style="min-height:200px;"></select>


                                </div>

                                <div class="col-md-2 text-center" style="margin-top:25px;">


                                    <div class="row" style="padding-bottom:10px;">
                                        <button type="button" title="Inserir item no destino" class="btn btn-default btn-add"><i class="glyph-icon icon-arrow-circle-right"></i><div class="ripple-wrapper"></div></button>
                                    </div>

                                    <div class="row">
                                        <button type="button" title="Remover item no destino" class="btn btn-default btn-del"><i class="glyph-icon icon-arrow-circle-left"></i><div class="ripple-wrapper"></div></button>
                                    </div>



                                </div>


                                <div class="col-md-5 text-center">
                                    <label for="Membros"> Membros célula destino</label>
                                    <select multiple class="form-control multi-select" style="min-height:200px" id="Membros" name="Membros"></select>
                                </div>


                            </div>









                        </div>





                        <div class="panel-heading">
                            <h3></h3>
                        </div>
                        <div class="panel-body">

                            <div class="col-md-12">
                                <p class="text-danger validacao" style="padding-bottom:10px;"></p>

                            </div>

                            <div style="overflow:auto">
                                <div class="col-md-10   btn-container" style="">
                                    <button type="submit" class="btn btn-space btn-primary">Salvar</button>
                                    <a href="@Url.Action("Index")" class="btn btn-space btn-default">Cancelar</a>
                                </div>

                            </div>




                        </div>


                    </div>

                </div>




            </div>
        </div>
    </div>





}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")



    <link href="~/Content/3rdParty/Template/widgets/chosen/chosen.css" rel="stylesheet" />
    <script src="~/Content/3rdParty/Template/widgets/chosen/chosen.js"></script>



    <style type="text/css">
        .chosen-single div:last-of-type {
            display: none;
        }
    </style>

    <script>

        var requestAtual;


        $(document).ready(function () {



            $(".chosen-select").chosen();

            //$("selector").chosen().change(function () {
            $("#id_origem").chosen().change(function () {

                //Carrega o numero da origem
                $("#txtnumero").val($("#id_origem").val().pad(4));


                //carrega o nome do supervisor de origem
                $("#txtsupervisor").val($("#id_origem option:selected").attr("nomesupervisor"));

                //limpa a lista de membros destino
                $("#Membros option").remove();
                $("#MembrosOrigem option").remove();

                if (typeof ($("#txtnumero").val()) == undefined || $("#txtnumero").val().lenght == 0) {
                    $("#dvdestino").hide();
                    return;
                }


                var urlBase = '@Url.Action("GetJsonParticipantes")/';

                //Carrega os itens disponíveis (membros da celula de origem)
                requestAtual = $.getJSON(urlBase + $("#id_origem").val(), function (data) {

                    $("#dvdestino").fadeIn(200);

                    $(data.data).each(function (idx, obj) {
                        $("#MembrosOrigem").append("<option id=" + obj.id_pessoa + ">" + obj.Nome + "</option>");
                    });


                }).fail(function () {
                    console.log("Erro ao executar comando no servidor")
                    });




            });//chosen change



            $(".btn-add").click(function () {

                var items = $("#MembrosOrigem option:selected");

                $(items).each(function (idx, obj) {

                    $("#Membros").append(obj);

                });



            });


            $(".btn-del").click(function () {

                var items = $("#Membros option:selected");

                $(items).each(function (idx, obj) {

                    $("#MembrosOrigem").append(obj);

                });

            });



            $("#frmMain").on("submit", function (e) {

                e.preventDefault;

                //valida o formulário
                if (!valida()) return false;

                //seleciona todos os itens da celula destino (o post so leva os itens selecionados)
                var arrMembros = [];
                $("#Membros option").each(function () {
                    arrMembros.push($(this).attr("id"));
                });

                //envia o POST
                   $.ajax({
                        url: '@Url.Content("~/Celulas/Multiplicar/")',
                        dataType: "json",
                        type: "POST",
                        contentType: 'application/json; charset=utf-8',
                       data: JSON.stringify({
                           id_origem: $("#id_origem").val(),
                           id_coordenador: $("#id_coordenador").val(),
                           id_supervisor: $("#id_supervisor").val(),
                           Membros : arrMembros
                       }),
                        async: true,
                        processData: false,
                        cache: false,
                       success: function (data) {

                           var urlBase = '@Url.Action("Editar","Celulas")';
                           //Redireciona para a recém criada célula. ( O ajax retorna o número da nova célula)
                           window.location = urlBase + "/" + data.id_celula;

                        },
                        error: function (xhr) {

                            var arrResp = $(xhr.responseText);

                            if (arrResp.length > 0) //A api retornou o erro, exibir o que está vindo da API
                            {
                                alert($(arrResp[1]).text());

                            } else //A api não retornou erro corretamente. Exibe mensagem genérica de erro
                            {
                                alert('Erro ao efetuar o comando no servidor');
                            }


                        }
                });

















                return false;

            });




        })//ready




        var valida = function () {

            var strValidacoes = "<strong>Não foi possível executar a ação pois os seguintes erros foram detectados:</strong>";
            var valido = true;


            //verifica se selecionou o cooredenador
            if (typeof ($("#id_coordenador").val()) == "undefined" || $("#id_coordenador").val().length == 0) {
                strValidacoes += "<br /> Favor informe o coordenador da célula de destino";
                valido = false;
            }


            //verifica se há membros selecionados
            if ($("#Membros option").length == 0) {
                strValidacoes += "<br/>É necessário incluir pelo menos um membro na célula de destino";
                valido = false;
            }

            if (!valido) {
                $(".validacao").html(strValidacoes).fadeIn();
            } else {
                $(".validacao").hide();
            }
            return valido;
        }




    </script>

}