bie.evgestao/1 - UI/1.1 - MVC/bie.evgestao.ui.mvc/Controllers/RelatoriosController.cs
using AutoMapper;
using bie.evgestao.application.Interfaces;
using bie.evgestao.domain.Entities;
using bie.evgestao.ui.viewmodels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace bie.evgestao.ui.mvc.Controllers
{
    public class RelatoriosController : BaseController
    {
        private readonly ICelulaAppService _svc_celula;
        private readonly IPessoaAppService _svc_pessoa;

        public RelatoriosController(ICelulaAppService svc1, IPessoaAppService svc2)
        {
            _svc_celula = svc1;
            _svc_pessoa = svc2;

        }



        public ActionResult FichaCelula()
        {
            var model = Mapper.Map<IEnumerable<Celula>, IEnumerable<CelulaViewmodel>>(_svc_celula.GetAll());
            return View(model);
        }

        public ActionResult Aniversariantes(int? mes)
        {

            var model = Mapper.Map<IEnumerable<Pessoa>, IEnumerable<PessoaViewmodel>>(
               _svc_pessoa.GetAll().Where(x => x.DataNascimento.HasValue && x.DataNascimento.Value.Month == (mes.HasValue ? mes : x.DataNascimento.Value.Month))
               );

            return View(model);

        }

    }
}

bie.evgestao/1 - UI/1.1 - MVC/bie.evgestao.ui.mvc/Views/Relatorios/Aniversariantes.cshtml
@model IEnumerable<bie.evgestao.ui.viewmodels.PessoaViewmodel>
@{
    ViewBag.Title = "Aniversariantes";
    ViewBag.HeaderText = ViewBag.Title;

    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div id="page-title">
    <h2>Aniversariantes</h2><p>
        Aniversariantes por mês
    </p>
</div>





@for (int i = 1; i <= 12; i++)
{
    <div class="col-md-1">
        <a class="btn btn-info" style="width:100%;text-transform: capitalize;" href='@Url.Action("Aniversariantes","Relatorios", new { mes=i })'>
            @System.Globalization.CultureInfo.CurrentCulture.DateTimeFormat.GetMonthName(i)
        </a>
    </div>

}
</ul>







<table class="table table-hover">

    <thead>
        <tr>
            <th>Nome</th>
            <th>Telefone</th>
            <th>Data Nascimento</th>
        </tr>
    </thead>

    @foreach (var item in Model)
    {
        <tr>
            <td>@item.Nome</td>
            <td>@Html.Raw(item.Tels)</td>
            <td>@item.DataNascimento.Value.ToShortDateString()</td>
        </tr>
    }

</table>

bie.evgestao/1 - UI/1.1 - MVC/bie.evgestao.ui.mvc/Views/Relatorios/FichaCelula.cshtml
@model IEnumerable<bie.evgestao.ui.viewmodels.CelulaViewmodel>
@{
    ViewBag.Title = "Ficha da célula";
    ViewBag.HeaderText = ViewBag.Title;

    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div id="page-title">
    <h2>Ficha da célula</h2><p>
        Listagem de células com detalhamento
    </p>
</div>


<table class="table table-hover ">

    <thead>
        <tr>
            <th>Número</th>
            <th>Coordenador</th>
            <th>Supervisor</th>
            <th>Endereço</th>
            <th>Criação</th>
            <th>Reunião</th>
            <th>Situação</th>
            <th>Participantes</th>
        </tr>

    </thead>


    @foreach (var celula in Model)
    {
        <tr>
            <td>
                @celula.id_celula.ToString().PadLeft(4, '0')
            </td>

            <td>
                @if (celula.Coordenador != null)
                {
                    @celula.Coordenador.Nome
                    <br />
                    @Html.Raw(celula.Coordenador.Tels)
                }
                else
                {
                    @:-
                }
            </td>

            <td>
                @if (celula.Supervisor != null)
                {
                    @celula.Supervisor.Nome
                    <br />
                    @Html.Raw(celula.Supervisor.Tels)
                }
                else
                {
                    @:-
                }
            </td>

            <td>
                @celula.Endereco @celula.Numero @celula.Complemento <br /> @celula.Bairro @celula.Cidade @celula.UF <br />
                cep: @celula.Cep
            </td>

            <td>
                @celula.DataCriacao.Value.ToShortDateString()
            </td>

            <td>
                @celula.DiaReuniaoDesc
            </td>

            <td>
                @celula.HoraReuniao
            </td>

            <td>
                @celula.SituacaoDesc
            </td>

            <td>
                <!-- inicio participantes -->

                @if (celula.Pessoas.Count > 0)
                {
                    <table class="table table-condensed">
                        <thead>
                            <tr>
                                <th>Nome</th>
                                <th>Atividade</th>
                                <th>Telefones</th>
                            </tr>
                        </thead>

                        @foreach (var pessoa in celula.Pessoas)
                        {
                            <tr>
                                <td>@pessoa.Nome</td>
                                <td>@pessoa.SituacaoDesc</td>
                                <td>@Html.Raw(pessoa.Tels)</td>
                            </tr>
                        }


                    </table>

                }
                else
                {
                    @:Nenhum parcitipante
                }


                <!-- fim participantes -->
            </td>









        </tr>


    }





</table>